#!/usr/bin/env python3
"""Compile checked-in Vulkan shaders to the embedded SPIR-V header."""
from pathlib import Path
import struct, subprocess, tempfile
root=Path(__file__).resolve().parents[1]
cpp=root/'platforms/android/runtime/src/main/cpp'
parts=['// Generated by scripts/build-android-shaders.py; edit shaders/ui.* instead.\n#pragma once\n#include <cstdint>\nnamespace podjs_gpu {\n']
with tempfile.TemporaryDirectory() as tmp:
    for stage,name in [('vert','vertex_spv'),('frag','fragment_spv')]:
        out=Path(tmp)/f'{stage}.spv'
        subprocess.run(['glslangValidator','-V','--target-env','vulkan1.1','-o',str(out),str(cpp/f'shaders/ui.{stage}')],check=True)
        subprocess.run(['spirv-val','--target-env','vulkan1.1',str(out)],check=True)
        data=out.read_bytes(); words=struct.unpack('<'+'I'*(len(data)//4),data)
        parts.append(f'alignas(4) static constexpr uint32_t {name}[] = {{\n')
        parts.extend('  '+','.join(f'0x{w:08x}' for w in words[i:i+8])+',\n' for i in range(0,len(words),8))
        parts.append('};\n')
parts.append('}\n')
(cpp/'gpu_shaders.h').write_text(''.join(parts))
